site_name: RO Translation Project Documentation
site_url: 'https://llchrisll.github.io/ROenglishRE/'
site_description: 'ROTP and Client-side Guides'
site_author: 'Houndeye aka llchrisll'
docs_dir: docs/
site_dir: _site/
repo_name: 'llchrisll/ROenglishRE/'
repo_url: 'https://github.com/llchrisll/ROenglishRE\'
nav:
    - Home: index.md
    - Guides:
      - Project Installation: guides/install.md
      - Client Features&Issues: guides/client.md
      - Web Service: guides/webservice.md
      - Customization: guides/customs.md
    - Addons: addons/index.md
    - FAQ: FAQ.md
    - Contribution: contribution.md
    
theme: ## https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
  icon:
    repo: fontawesome/brands/github-alt
  name: 'material'
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: red
      accent: orange
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/llchrisll/ROenglishRE/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sagbPhH

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/smoothScrolling.js
